version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: "increase"
    labels:
      - "dependencies"
      - "npm"
    reviewers:
      - "bossboxing"
    assignees:
      - "bossboxing"
    ignore:
      - dependency-name: "next"
        versions: ["beta", "alpha"]
      - dependency-name: "react"
        versions: ["beta", "alpha"]
      - dependency-name: "react-dom"
        versions: ["beta", "alpha"]